name: Lands-Outposts continuous delivery

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: lands-outposts
        path: target/lands-outposts.jar
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: lands-outposts
          
      - name: Clone Plugins Project
        run: |
          git config --global user.name "octocroissant[bot]"
          git config --global user.email 149737708+octocroissant[bot]@users.noreply.github.com
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git clone https://octocroissant[bot]:${{ secrets.PAT_TOKEN }}@github.com/LaBoulangerie/Server.git
          cp lands-outposts.jar Server/plugins/
          cd Server
          git add .
          git commit -m "Update artifact from $GITHUB_REPOSITORY"
          git push
